#pragma checksum "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1616CA7D58D1B7AFE071348347F786507930A7EF"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO.xaml.Main {
    
    
    /// <summary>
    /// TrainingModuleWindow
    /// </summary>
    public partial class TrainingModuleWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel WraPanel;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label fgdLabel1;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Fgd;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnInstrumentOperation;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label fgdLabel2;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label jtjLabel1;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Jtj;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnReagentOperation;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label jtjLabel2;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border cy;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSampling;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border px;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnFoodSecurityAct;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border syaq;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSecurity;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnInstrumentOperation1;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnReagentOperation1;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/main/trainingmodulewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 20 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.WraPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 3:
            this.fgdLabel1 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.Fgd = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.BtnInstrumentOperation = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnInstrumentOperation.Click += new System.Windows.RoutedEventHandler(this.BtnInstrumentOperation_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.fgdLabel2 = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.jtjLabel1 = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.Jtj = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.BtnReagentOperation = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnReagentOperation.Click += new System.Windows.RoutedEventHandler(this.BtnReagentOperation_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.jtjLabel2 = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.cy = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.BtnSampling = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnSampling.Click += new System.Windows.RoutedEventHandler(this.BtnSampling_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.px = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.BtnFoodSecurityAct = ((System.Windows.Controls.Button)(target));
            
            #line 61 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnFoodSecurityAct.Click += new System.Windows.RoutedEventHandler(this.BtnFoodSecurityAct_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.syaq = ((System.Windows.Controls.Border)(target));
            return;
            case 16:
            this.BtnSecurity = ((System.Windows.Controls.Button)(target));
            
            #line 72 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnSecurity.Click += new System.Windows.RoutedEventHandler(this.BtnSecurity_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BtnInstrumentOperation1 = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnInstrumentOperation1.Click += new System.Windows.RoutedEventHandler(this.BtnInstrumentOperation1_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.BtnReagentOperation1 = ((System.Windows.Controls.Button)(target));
            
            #line 98 "..\..\..\..\xaml\Main\TrainingModuleWindow.xaml"
            this.BtnReagentOperation1.Click += new System.Windows.RoutedEventHandler(this.BtnReagentOperation1_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

