//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WorkstationUI.WebReference1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="instrumentDockingServiceProviderServiceBinding", Namespace="http://www.zhiyunda.com/service/instrumentDockingService")]
    public partial class instrumentDockingServiceProviderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private @string userNameField;
        
        private string1 keyField;
        
        private string2 interfaceVersionField;
        
        private System.Threading.SendOrPostCallback instrumentDictionaryHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback instrumentInfoHandleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public instrumentDockingServiceProviderService() {
            this.Url = global::WorkstationUI.Properties.Settings.Default.数据采集系统_WebReference1_instrumentDockingServiceProviderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public @string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        public string1 key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        public string2 interfaceVersion {
            get {
                return this.interfaceVersionField;
            }
            set {
                this.interfaceVersionField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event instrumentDictionaryHandleCompletedEventHandler instrumentDictionaryHandleCompleted;
        
        /// <remarks/>
        public event instrumentInfoHandleCompletedEventHandler instrumentInfoHandleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("key")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("interfaceVersion")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("userName")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("instrumentDictionaryResponse", Namespace="http://www.zhiyunda.com/zydjcy")]
        public instrumentDictionaryResponse instrumentDictionaryHandle([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.zhiyunda.com/zydjcy")] instrumentDictionaryRequest instrumentDictionaryRequest) {
            object[] results = this.Invoke("instrumentDictionaryHandle", new object[] {
                        instrumentDictionaryRequest});
            return ((instrumentDictionaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void instrumentDictionaryHandleAsync(instrumentDictionaryRequest instrumentDictionaryRequest) {
            this.instrumentDictionaryHandleAsync(instrumentDictionaryRequest, null);
        }
        
        /// <remarks/>
        public void instrumentDictionaryHandleAsync(instrumentDictionaryRequest instrumentDictionaryRequest, object userState) {
            if ((this.instrumentDictionaryHandleOperationCompleted == null)) {
                this.instrumentDictionaryHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OninstrumentDictionaryHandleOperationCompleted);
            }
            this.InvokeAsync("instrumentDictionaryHandle", new object[] {
                        instrumentDictionaryRequest}, this.instrumentDictionaryHandleOperationCompleted, userState);
        }
        
        private void OninstrumentDictionaryHandleOperationCompleted(object arg) {
            if ((this.instrumentDictionaryHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.instrumentDictionaryHandleCompleted(this, new instrumentDictionaryHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("key")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("interfaceVersion")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("userName")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("instrumentInfoResponse", Namespace="http://www.zhiyunda.com/zydjcy")]
        public instrumentInfoResponse instrumentInfoHandle([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.zhiyunda.com/zydjcy")] [System.Xml.Serialization.XmlArrayItemAttribute("instrumentDockingInfoList")] instrumentDockingInfo[] instrumentInfoRequest) {
            object[] results = this.Invoke("instrumentInfoHandle", new object[] {
                        instrumentInfoRequest});
            return ((instrumentInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void instrumentInfoHandleAsync(instrumentDockingInfo[] instrumentInfoRequest) {
            this.instrumentInfoHandleAsync(instrumentInfoRequest, null);
        }
        
        /// <remarks/>
        public void instrumentInfoHandleAsync(instrumentDockingInfo[] instrumentInfoRequest, object userState) {
            if ((this.instrumentInfoHandleOperationCompleted == null)) {
                this.instrumentInfoHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OninstrumentInfoHandleOperationCompleted);
            }
            this.InvokeAsync("instrumentInfoHandle", new object[] {
                        instrumentInfoRequest}, this.instrumentInfoHandleOperationCompleted, userState);
        }
        
        private void OninstrumentInfoHandleOperationCompleted(object arg) {
            if ((this.instrumentInfoHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.instrumentInfoHandleCompleted(this, new instrumentInfoHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="string", Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("key", Namespace="http://www.zhiyunda.com/service/instrumentDockingService", IsNullable=true)]
    public partial class string1 : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="string", Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("interfaceVersion", Namespace="http://www.zhiyunda.com/service/instrumentDockingService", IsNullable=true)]
    public partial class string2 : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("userName", Namespace="http://www.zhiyunda.com/service/instrumentDockingService", IsNullable=true)]
    public partial class @string : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zhiyunda.com/zydjcy")]
    public partial class instrumentDictionaryRequest {
        
        private string instrumentField;
        
        private string instrumentNoField;
        
        private string macField;
        
        private string tableDataField;
        
        private string reqTypeField;
        
        /// <remarks/>
        public string instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }
        
        /// <remarks/>
        public string instrumentNo {
            get {
                return this.instrumentNoField;
            }
            set {
                this.instrumentNoField = value;
            }
        }
        
        /// <remarks/>
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        public string tableData {
            get {
                return this.tableDataField;
            }
            set {
                this.tableDataField = value;
            }
        }
        
        /// <remarks/>
        public string reqType {
            get {
                return this.reqTypeField;
            }
            set {
                this.reqTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zhiyunda.com/zydjcy")]
    public partial class instrumentDockingInfo {
        
        private string instrumentField;
        
        private string instrumentNoField;
        
        private string gpsField;
        
        private string macField;
        
        private string fTpyeField;
        
        private string fNameField;
        
        private string tradeMarkField;
        
        private string foodcodeField;
        
        private string proBatchField;
        
        private string proDateField;
        
        private string proSpecificationsField;
        
        private string manuUnitField;
        
        private string checkedNoField;
        
        private string sampleNoField;
        
        private string checkedUnitField;
        
        private string dataNumField;
        
        private string testProField;
        
        private string quanOrQualField;
        
        private string contentsField;
        
        private string unitField;
        
        private string testResultField;
        
        private string dilutionRaField;
        
        private string testRangeField;
        
        private string standardLimitField;
        
        private string basedStandardField;
        
        private string testPersonField;
        
        private string testTimeField;
        
        private string sampleTimeField;
        
        private string remarkField;
        
        private string reserve1Field;
        
        private string reserve2Field;
        
        private string reserve3Field;
        
        private string reserve4Field;
        
        private string reserve5Field;
        
        /// <remarks/>
        public string instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }
        
        /// <remarks/>
        public string instrumentNo {
            get {
                return this.instrumentNoField;
            }
            set {
                this.instrumentNoField = value;
            }
        }
        
        /// <remarks/>
        public string gps {
            get {
                return this.gpsField;
            }
            set {
                this.gpsField = value;
            }
        }
        
        /// <remarks/>
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        public string fTpye {
            get {
                return this.fTpyeField;
            }
            set {
                this.fTpyeField = value;
            }
        }
        
        /// <remarks/>
        public string fName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
            }
        }
        
        /// <remarks/>
        public string tradeMark {
            get {
                return this.tradeMarkField;
            }
            set {
                this.tradeMarkField = value;
            }
        }
        
        /// <remarks/>
        public string foodcode {
            get {
                return this.foodcodeField;
            }
            set {
                this.foodcodeField = value;
            }
        }
        
        /// <remarks/>
        public string proBatch {
            get {
                return this.proBatchField;
            }
            set {
                this.proBatchField = value;
            }
        }
        
        /// <remarks/>
        public string proDate {
            get {
                return this.proDateField;
            }
            set {
                this.proDateField = value;
            }
        }
        
        /// <remarks/>
        public string proSpecifications {
            get {
                return this.proSpecificationsField;
            }
            set {
                this.proSpecificationsField = value;
            }
        }
        
        /// <remarks/>
        public string manuUnit {
            get {
                return this.manuUnitField;
            }
            set {
                this.manuUnitField = value;
            }
        }
        
        /// <remarks/>
        public string checkedNo {
            get {
                return this.checkedNoField;
            }
            set {
                this.checkedNoField = value;
            }
        }
        
        /// <remarks/>
        public string sampleNo {
            get {
                return this.sampleNoField;
            }
            set {
                this.sampleNoField = value;
            }
        }
        
        /// <remarks/>
        public string checkedUnit {
            get {
                return this.checkedUnitField;
            }
            set {
                this.checkedUnitField = value;
            }
        }
        
        /// <remarks/>
        public string dataNum {
            get {
                return this.dataNumField;
            }
            set {
                this.dataNumField = value;
            }
        }
        
        /// <remarks/>
        public string testPro {
            get {
                return this.testProField;
            }
            set {
                this.testProField = value;
            }
        }
        
        /// <remarks/>
        public string quanOrQual {
            get {
                return this.quanOrQualField;
            }
            set {
                this.quanOrQualField = value;
            }
        }
        
        /// <remarks/>
        public string contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string testResult {
            get {
                return this.testResultField;
            }
            set {
                this.testResultField = value;
            }
        }
        
        /// <remarks/>
        public string dilutionRa {
            get {
                return this.dilutionRaField;
            }
            set {
                this.dilutionRaField = value;
            }
        }
        
        /// <remarks/>
        public string testRange {
            get {
                return this.testRangeField;
            }
            set {
                this.testRangeField = value;
            }
        }
        
        /// <remarks/>
        public string standardLimit {
            get {
                return this.standardLimitField;
            }
            set {
                this.standardLimitField = value;
            }
        }
        
        /// <remarks/>
        public string basedStandard {
            get {
                return this.basedStandardField;
            }
            set {
                this.basedStandardField = value;
            }
        }
        
        /// <remarks/>
        public string testPerson {
            get {
                return this.testPersonField;
            }
            set {
                this.testPersonField = value;
            }
        }
        
        /// <remarks/>
        public string testTime {
            get {
                return this.testTimeField;
            }
            set {
                this.testTimeField = value;
            }
        }
        
        /// <remarks/>
        public string sampleTime {
            get {
                return this.sampleTimeField;
            }
            set {
                this.sampleTimeField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string reserve1 {
            get {
                return this.reserve1Field;
            }
            set {
                this.reserve1Field = value;
            }
        }
        
        /// <remarks/>
        public string reserve2 {
            get {
                return this.reserve2Field;
            }
            set {
                this.reserve2Field = value;
            }
        }
        
        /// <remarks/>
        public string reserve3 {
            get {
                return this.reserve3Field;
            }
            set {
                this.reserve3Field = value;
            }
        }
        
        /// <remarks/>
        public string reserve4 {
            get {
                return this.reserve4Field;
            }
            set {
                this.reserve4Field = value;
            }
        }
        
        /// <remarks/>
        public string reserve5 {
            get {
                return this.reserve5Field;
            }
            set {
                this.reserve5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zhiyunda.com/zydjcy")]
    public partial class instrumentDictionaryResponse {
        
        private string statusField;
        
        private string descriptionField;
        
        private string tableUpdateTimeField;
        
        private string updateDataField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string tableUpdateTime {
            get {
                return this.tableUpdateTimeField;
            }
            set {
                this.tableUpdateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string updateData {
            get {
                return this.updateDataField;
            }
            set {
                this.updateDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.zhiyunda.com/zydjcy")]
    public partial class instrumentInfoResponse {
        
        private string statusField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void instrumentDictionaryHandleCompletedEventHandler(object sender, instrumentDictionaryHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class instrumentDictionaryHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal instrumentDictionaryHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public instrumentDictionaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((instrumentDictionaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void instrumentInfoHandleCompletedEventHandler(object sender, instrumentInfoHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class instrumentInfoHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal instrumentInfoHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public instrumentInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((instrumentInfoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591