#pragma checksum "..\..\..\..\xaml\Print\ReportWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "07CEB63B6132B0043639B3C5BCA42ABD"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO.xaml.Print {
    
    
    /// <summary>
    /// ReportWindow
    /// </summary>
    public partial class ReportWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSearch;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnPrint;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDeleted;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDeletedAll;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnPrintHZ;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label CheckBoxUser;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ComboBoxCheckUnitName;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label CheckBoxItem;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ComboBoxCheckedCompanyName;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Search;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRecord;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu DataGridMenu;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miEdit;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miReportPrint;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miDeleted;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dataGridGS;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu contextMenu1;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miEditGS;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miReportPrintGS;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miReportPrintGSHZ;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\xaml\Print\ReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miDeletedGS;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/print/reportwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            ((AIO.xaml.Print.ReportWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnSearch = ((System.Windows.Controls.Button)(target));
            
            #line 20 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.btnSearch.Click += new System.Windows.RoutedEventHandler(this.btnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.btnUpdate.Click += new System.Windows.RoutedEventHandler(this.btnUpdate_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnPrint = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.btnPrint.Click += new System.Windows.RoutedEventHandler(this.btnPrint_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btnDeleted = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.btnDeleted.Click += new System.Windows.RoutedEventHandler(this.btnDeleted_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btnDeletedAll = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.btnDeletedAll.Click += new System.Windows.RoutedEventHandler(this.btnDeletedAll_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btnPrintHZ = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.btnPrintHZ.Click += new System.Windows.RoutedEventHandler(this.btnPrintHZ_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.CheckBoxUser = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.ComboBoxCheckUnitName = ((System.Windows.Controls.TextBox)(target));
            
            #line 36 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.ComboBoxCheckUnitName.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.ComboBoxCheckUnitName_TextChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.CheckBoxItem = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.ComboBoxCheckedCompanyName = ((System.Windows.Controls.TextBox)(target));
            
            #line 40 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.ComboBoxCheckedCompanyName.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.ComboBoxCheckedCompanyName_TextChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.Search = ((System.Windows.Controls.Button)(target));
            
            #line 41 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.Search.Click += new System.Windows.RoutedEventHandler(this.btnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.DataGridRecord = ((System.Windows.Controls.DataGrid)(target));
            
            #line 48 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.DataGridRecord.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.DataGridRecord_LoadingRow);
            
            #line default
            #line hidden
            
            #line 48 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.DataGridRecord.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.DataGridRecord_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 15:
            this.DataGridMenu = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 16:
            this.miEdit = ((System.Windows.Controls.MenuItem)(target));
            
            #line 51 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miEdit.Click += new System.Windows.RoutedEventHandler(this.miEdit_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.miReportPrint = ((System.Windows.Controls.MenuItem)(target));
            
            #line 52 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miReportPrint.Click += new System.Windows.RoutedEventHandler(this.miReportPrint_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.miDeleted = ((System.Windows.Controls.MenuItem)(target));
            
            #line 53 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miDeleted.Click += new System.Windows.RoutedEventHandler(this.miDeleted_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.dataGridGS = ((System.Windows.Controls.DataGrid)(target));
            
            #line 80 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.dataGridGS.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.dataGridGS_MouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 80 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.dataGridGS.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.dataGridGS_LoadingRow);
            
            #line default
            #line hidden
            return;
            case 20:
            this.contextMenu1 = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 21:
            this.miEditGS = ((System.Windows.Controls.MenuItem)(target));
            
            #line 110 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miEditGS.Click += new System.Windows.RoutedEventHandler(this.miEditGS_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.miReportPrintGS = ((System.Windows.Controls.MenuItem)(target));
            
            #line 111 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miReportPrintGS.Click += new System.Windows.RoutedEventHandler(this.miReportPrintGS_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.miReportPrintGSHZ = ((System.Windows.Controls.MenuItem)(target));
            
            #line 112 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miReportPrintGSHZ.Click += new System.Windows.RoutedEventHandler(this.miReportPrintGSHZ_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.miDeletedGS = ((System.Windows.Controls.MenuItem)(target));
            
            #line 113 "..\..\..\..\xaml\Print\ReportWindow.xaml"
            this.miDeletedGS.Click += new System.Windows.RoutedEventHandler(this.miDeletedGS_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

