//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WorkstationUI.com.szscgl.ncp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="sDataInfraceSoap", Namespace="http://tempuri.org/")]
    public partial class sDataInfrace : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkInOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveQuickCheckItemInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback savePurchaseBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveSalesBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveUnitQuickInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveRegisterQuickSNOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryMarketOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySignContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCheckItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySalesItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSignContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaMarketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaSignContactOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public sDataInfrace() {
            this.Url = global::WorkstationUI.Properties.Settings.Default.数据采集系统_com_szscgl_ncp_sDataInfrace;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkInCompletedEventHandler checkInCompleted;
        
        /// <remarks/>
        public event checkOutCompletedEventHandler checkOutCompleted;
        
        /// <remarks/>
        public event saveQuickCheckItemInfoCompletedEventHandler saveQuickCheckItemInfoCompleted;
        
        /// <remarks/>
        public event savePurchaseBillCompletedEventHandler savePurchaseBillCompleted;
        
        /// <remarks/>
        public event saveSalesBillCompletedEventHandler saveSalesBillCompleted;
        
        /// <remarks/>
        public event saveUnitQuickInfoCompletedEventHandler saveUnitQuickInfoCompleted;
        
        /// <remarks/>
        public event saveRegisterQuickSNCompletedEventHandler saveRegisterQuickSNCompleted;
        
        /// <remarks/>
        public event QueryMarketCompletedEventHandler QueryMarketCompleted;
        
        /// <remarks/>
        public event QuerySignContactCompletedEventHandler QuerySignContactCompleted;
        
        /// <remarks/>
        public event QueryCheckItemCompletedEventHandler QueryCheckItemCompleted;
        
        /// <remarks/>
        public event QuerySalesItemCompletedEventHandler QuerySalesItemCompleted;
        
        /// <remarks/>
        public event GetSignContactCompletedEventHandler GetSignContactCompleted;
        
        /// <remarks/>
        public event GetAreaMarketCompletedEventHandler GetAreaMarketCompleted;
        
        /// <remarks/>
        public event GetAreaSignContactCompletedEventHandler GetAreaSignContactCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkIn(string strXML) {
            object[] results = this.Invoke("checkIn", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkInAsync(string strXML) {
            this.checkInAsync(strXML, null);
        }
        
        /// <remarks/>
        public void checkInAsync(string strXML, object userState) {
            if ((this.checkInOperationCompleted == null)) {
                this.checkInOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckInOperationCompleted);
            }
            this.InvokeAsync("checkIn", new object[] {
                        strXML}, this.checkInOperationCompleted, userState);
        }
        
        private void OncheckInOperationCompleted(object arg) {
            if ((this.checkInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkInCompleted(this, new checkInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkOut(string strXML) {
            object[] results = this.Invoke("checkOut", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkOutAsync(string strXML) {
            this.checkOutAsync(strXML, null);
        }
        
        /// <remarks/>
        public void checkOutAsync(string strXML, object userState) {
            if ((this.checkOutOperationCompleted == null)) {
                this.checkOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckOutOperationCompleted);
            }
            this.InvokeAsync("checkOut", new object[] {
                        strXML}, this.checkOutOperationCompleted, userState);
        }
        
        private void OncheckOutOperationCompleted(object arg) {
            if ((this.checkOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkOutCompleted(this, new checkOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveQuickCheckItemInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string saveQuickCheckItemInfo(string strXML) {
            object[] results = this.Invoke("saveQuickCheckItemInfo", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveQuickCheckItemInfoAsync(string strXML) {
            this.saveQuickCheckItemInfoAsync(strXML, null);
        }
        
        /// <remarks/>
        public void saveQuickCheckItemInfoAsync(string strXML, object userState) {
            if ((this.saveQuickCheckItemInfoOperationCompleted == null)) {
                this.saveQuickCheckItemInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveQuickCheckItemInfoOperationCompleted);
            }
            this.InvokeAsync("saveQuickCheckItemInfo", new object[] {
                        strXML}, this.saveQuickCheckItemInfoOperationCompleted, userState);
        }
        
        private void OnsaveQuickCheckItemInfoOperationCompleted(object arg) {
            if ((this.saveQuickCheckItemInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveQuickCheckItemInfoCompleted(this, new saveQuickCheckItemInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/savePurchaseBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string savePurchaseBill(string strXML) {
            object[] results = this.Invoke("savePurchaseBill", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void savePurchaseBillAsync(string strXML) {
            this.savePurchaseBillAsync(strXML, null);
        }
        
        /// <remarks/>
        public void savePurchaseBillAsync(string strXML, object userState) {
            if ((this.savePurchaseBillOperationCompleted == null)) {
                this.savePurchaseBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsavePurchaseBillOperationCompleted);
            }
            this.InvokeAsync("savePurchaseBill", new object[] {
                        strXML}, this.savePurchaseBillOperationCompleted, userState);
        }
        
        private void OnsavePurchaseBillOperationCompleted(object arg) {
            if ((this.savePurchaseBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.savePurchaseBillCompleted(this, new savePurchaseBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveSalesBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string saveSalesBill(string strXML) {
            object[] results = this.Invoke("saveSalesBill", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveSalesBillAsync(string strXML) {
            this.saveSalesBillAsync(strXML, null);
        }
        
        /// <remarks/>
        public void saveSalesBillAsync(string strXML, object userState) {
            if ((this.saveSalesBillOperationCompleted == null)) {
                this.saveSalesBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveSalesBillOperationCompleted);
            }
            this.InvokeAsync("saveSalesBill", new object[] {
                        strXML}, this.saveSalesBillOperationCompleted, userState);
        }
        
        private void OnsaveSalesBillOperationCompleted(object arg) {
            if ((this.saveSalesBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveSalesBillCompleted(this, new saveSalesBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveUnitQuickInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string saveUnitQuickInfo(string strXML) {
            object[] results = this.Invoke("saveUnitQuickInfo", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveUnitQuickInfoAsync(string strXML) {
            this.saveUnitQuickInfoAsync(strXML, null);
        }
        
        /// <remarks/>
        public void saveUnitQuickInfoAsync(string strXML, object userState) {
            if ((this.saveUnitQuickInfoOperationCompleted == null)) {
                this.saveUnitQuickInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveUnitQuickInfoOperationCompleted);
            }
            this.InvokeAsync("saveUnitQuickInfo", new object[] {
                        strXML}, this.saveUnitQuickInfoOperationCompleted, userState);
        }
        
        private void OnsaveUnitQuickInfoOperationCompleted(object arg) {
            if ((this.saveUnitQuickInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveUnitQuickInfoCompleted(this, new saveUnitQuickInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveRegisterQuickSN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string saveRegisterQuickSN(string strXML) {
            object[] results = this.Invoke("saveRegisterQuickSN", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveRegisterQuickSNAsync(string strXML) {
            this.saveRegisterQuickSNAsync(strXML, null);
        }
        
        /// <remarks/>
        public void saveRegisterQuickSNAsync(string strXML, object userState) {
            if ((this.saveRegisterQuickSNOperationCompleted == null)) {
                this.saveRegisterQuickSNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveRegisterQuickSNOperationCompleted);
            }
            this.InvokeAsync("saveRegisterQuickSN", new object[] {
                        strXML}, this.saveRegisterQuickSNOperationCompleted, userState);
        }
        
        private void OnsaveRegisterQuickSNOperationCompleted(object arg) {
            if ((this.saveRegisterQuickSNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveRegisterQuickSNCompleted(this, new saveRegisterQuickSNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryMarket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryMarket(string strXML) {
            object[] results = this.Invoke("QueryMarket", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryMarketAsync(string strXML) {
            this.QueryMarketAsync(strXML, null);
        }
        
        /// <remarks/>
        public void QueryMarketAsync(string strXML, object userState) {
            if ((this.QueryMarketOperationCompleted == null)) {
                this.QueryMarketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryMarketOperationCompleted);
            }
            this.InvokeAsync("QueryMarket", new object[] {
                        strXML}, this.QueryMarketOperationCompleted, userState);
        }
        
        private void OnQueryMarketOperationCompleted(object arg) {
            if ((this.QueryMarketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryMarketCompleted(this, new QueryMarketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuerySignContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QuerySignContact(string strXML) {
            object[] results = this.Invoke("QuerySignContact", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySignContactAsync(string strXML) {
            this.QuerySignContactAsync(strXML, null);
        }
        
        /// <remarks/>
        public void QuerySignContactAsync(string strXML, object userState) {
            if ((this.QuerySignContactOperationCompleted == null)) {
                this.QuerySignContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySignContactOperationCompleted);
            }
            this.InvokeAsync("QuerySignContact", new object[] {
                        strXML}, this.QuerySignContactOperationCompleted, userState);
        }
        
        private void OnQuerySignContactOperationCompleted(object arg) {
            if ((this.QuerySignContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySignContactCompleted(this, new QuerySignContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryCheckItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryCheckItem(string strXML) {
            object[] results = this.Invoke("QueryCheckItem", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCheckItemAsync(string strXML) {
            this.QueryCheckItemAsync(strXML, null);
        }
        
        /// <remarks/>
        public void QueryCheckItemAsync(string strXML, object userState) {
            if ((this.QueryCheckItemOperationCompleted == null)) {
                this.QueryCheckItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCheckItemOperationCompleted);
            }
            this.InvokeAsync("QueryCheckItem", new object[] {
                        strXML}, this.QueryCheckItemOperationCompleted, userState);
        }
        
        private void OnQueryCheckItemOperationCompleted(object arg) {
            if ((this.QueryCheckItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCheckItemCompleted(this, new QueryCheckItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuerySalesItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QuerySalesItem(string strXML) {
            object[] results = this.Invoke("QuerySalesItem", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySalesItemAsync(string strXML) {
            this.QuerySalesItemAsync(strXML, null);
        }
        
        /// <remarks/>
        public void QuerySalesItemAsync(string strXML, object userState) {
            if ((this.QuerySalesItemOperationCompleted == null)) {
                this.QuerySalesItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySalesItemOperationCompleted);
            }
            this.InvokeAsync("QuerySalesItem", new object[] {
                        strXML}, this.QuerySalesItemOperationCompleted, userState);
        }
        
        private void OnQuerySalesItemOperationCompleted(object arg) {
            if ((this.QuerySalesItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySalesItemCompleted(this, new QuerySalesItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSignContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSignContact(string strXML) {
            object[] results = this.Invoke("GetSignContact", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSignContactAsync(string strXML) {
            this.GetSignContactAsync(strXML, null);
        }
        
        /// <remarks/>
        public void GetSignContactAsync(string strXML, object userState) {
            if ((this.GetSignContactOperationCompleted == null)) {
                this.GetSignContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSignContactOperationCompleted);
            }
            this.InvokeAsync("GetSignContact", new object[] {
                        strXML}, this.GetSignContactOperationCompleted, userState);
        }
        
        private void OnGetSignContactOperationCompleted(object arg) {
            if ((this.GetSignContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSignContactCompleted(this, new GetSignContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreaMarket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreaMarket(string strXML) {
            object[] results = this.Invoke("GetAreaMarket", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaMarketAsync(string strXML) {
            this.GetAreaMarketAsync(strXML, null);
        }
        
        /// <remarks/>
        public void GetAreaMarketAsync(string strXML, object userState) {
            if ((this.GetAreaMarketOperationCompleted == null)) {
                this.GetAreaMarketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaMarketOperationCompleted);
            }
            this.InvokeAsync("GetAreaMarket", new object[] {
                        strXML}, this.GetAreaMarketOperationCompleted, userState);
        }
        
        private void OnGetAreaMarketOperationCompleted(object arg) {
            if ((this.GetAreaMarketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaMarketCompleted(this, new GetAreaMarketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreaSignContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreaSignContact(string strXML) {
            object[] results = this.Invoke("GetAreaSignContact", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaSignContactAsync(string strXML) {
            this.GetAreaSignContactAsync(strXML, null);
        }
        
        /// <remarks/>
        public void GetAreaSignContactAsync(string strXML, object userState) {
            if ((this.GetAreaSignContactOperationCompleted == null)) {
                this.GetAreaSignContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaSignContactOperationCompleted);
            }
            this.InvokeAsync("GetAreaSignContact", new object[] {
                        strXML}, this.GetAreaSignContactOperationCompleted, userState);
        }
        
        private void OnGetAreaSignContactOperationCompleted(object arg) {
            if ((this.GetAreaSignContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaSignContactCompleted(this, new GetAreaSignContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void checkInCompletedEventHandler(object sender, checkInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void checkOutCompletedEventHandler(object sender, checkOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void saveQuickCheckItemInfoCompletedEventHandler(object sender, saveQuickCheckItemInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveQuickCheckItemInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveQuickCheckItemInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void savePurchaseBillCompletedEventHandler(object sender, savePurchaseBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class savePurchaseBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal savePurchaseBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void saveSalesBillCompletedEventHandler(object sender, saveSalesBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveSalesBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveSalesBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void saveUnitQuickInfoCompletedEventHandler(object sender, saveUnitQuickInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveUnitQuickInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveUnitQuickInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void saveRegisterQuickSNCompletedEventHandler(object sender, saveRegisterQuickSNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveRegisterQuickSNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveRegisterQuickSNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void QueryMarketCompletedEventHandler(object sender, QueryMarketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryMarketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryMarketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void QuerySignContactCompletedEventHandler(object sender, QuerySignContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySignContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySignContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void QueryCheckItemCompletedEventHandler(object sender, QueryCheckItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCheckItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCheckItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void QuerySalesItemCompletedEventHandler(object sender, QuerySalesItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySalesItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySalesItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSignContactCompletedEventHandler(object sender, GetSignContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSignContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSignContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAreaMarketCompletedEventHandler(object sender, GetAreaMarketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaMarketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaMarketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAreaSignContactCompletedEventHandler(object sender, GetAreaSignContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaSignContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaSignContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591