#pragma checksum "..\..\..\..\xaml\KjService\SearchCompanys.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3CB9E02EC6A8C3B66C7C9CFA4886D1F50D336D97"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO.xaml.KjService {
    
    
    /// <summary>
    /// SearchCompanys
    /// </summary>
    public partial class SearchCompanys : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRecord;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu DataGridMenu;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miSelected;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miSearch;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miSearchB;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRecord_B;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miSelected_B;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem miBack;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtVal;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Search;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_Selected;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_SearchBusiness;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/kjservice/searchcompanys.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 5 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            ((AIO.xaml.KjService.SearchCompanys)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.DataGridRecord = ((System.Windows.Controls.DataGrid)(target));
            
            #line 10 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.DataGridRecord.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DataGridRecord_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 10 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.DataGridRecord.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.DataGridRecord_MouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 10 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.DataGridRecord.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.DataGridRecord_LoadingRow);
            
            #line default
            #line hidden
            return;
            case 3:
            this.DataGridMenu = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 4:
            this.miSelected = ((System.Windows.Controls.MenuItem)(target));
            
            #line 13 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.miSelected.Click += new System.Windows.RoutedEventHandler(this.Selected_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.miSearch = ((System.Windows.Controls.MenuItem)(target));
            
            #line 14 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.miSearch.Click += new System.Windows.RoutedEventHandler(this.Search_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.miSearchB = ((System.Windows.Controls.MenuItem)(target));
            
            #line 15 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.miSearchB.Click += new System.Windows.RoutedEventHandler(this.Btn_SearchBusiness_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.DataGridRecord_B = ((System.Windows.Controls.DataGrid)(target));
            
            #line 43 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.DataGridRecord_B.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DataGridRecord_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 43 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.DataGridRecord_B.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.DataGridRecord_MouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 43 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.DataGridRecord_B.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.DataGridRecord_LoadingRow);
            
            #line default
            #line hidden
            return;
            case 8:
            this.miSelected_B = ((System.Windows.Controls.MenuItem)(target));
            
            #line 46 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.miSelected_B.Click += new System.Windows.RoutedEventHandler(this.Selected_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.miBack = ((System.Windows.Controls.MenuItem)(target));
            
            #line 47 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.miBack.Click += new System.Windows.RoutedEventHandler(this.miBack_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.txtVal = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.Btn_Search = ((System.Windows.Controls.Button)(target));
            
            #line 71 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.Btn_Search.Click += new System.Windows.RoutedEventHandler(this.Search_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.Btn_Selected = ((System.Windows.Controls.Button)(target));
            
            #line 72 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.Btn_Selected.Click += new System.Windows.RoutedEventHandler(this.Selected_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.Btn_SearchBusiness = ((System.Windows.Controls.Button)(target));
            
            #line 73 "..\..\..\..\xaml\KjService\SearchCompanys.xaml"
            this.Btn_SearchBusiness.Click += new System.Windows.RoutedEventHandler(this.Btn_SearchBusiness_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

