//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace AIO.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StandardInterfaceSoap11Binding", Namespace="http://webservice.lhfs.com")]
    public partial class StandardInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getFoodTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadPlatformStallDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadPlatformDetectionDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadGpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadPlatformEnterpriseDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTestItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEnterprisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadDetectionDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStallsOperationCompleted;
        
        private System.Threading.SendOrPostCallback equipmentRegisterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StandardInterface() {
            this.Url = global::AIO.Properties.Settings.Default.DY_Detector_WebReference_StandardInterface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getFoodTypesCompletedEventHandler getFoodTypesCompleted;
        
        /// <remarks/>
        public event uploadPlatformStallDataCompletedEventHandler uploadPlatformStallDataCompleted;
        
        /// <remarks/>
        public event uploadPlatformDetectionDataCompletedEventHandler uploadPlatformDetectionDataCompleted;
        
        /// <remarks/>
        public event uploadGpsCompletedEventHandler uploadGpsCompleted;
        
        /// <remarks/>
        public event uploadPlatformEnterpriseDataCompletedEventHandler uploadPlatformEnterpriseDataCompleted;
        
        /// <remarks/>
        public event getTestItemsCompletedEventHandler getTestItemsCompleted;
        
        /// <remarks/>
        public event getEnterprisesCompletedEventHandler getEnterprisesCompleted;
        
        /// <remarks/>
        public event uploadDetectionDataCompletedEventHandler uploadDetectionDataCompleted;
        
        /// <remarks/>
        public event getProductsCompletedEventHandler getProductsCompleted;
        
        /// <remarks/>
        public event getStallsCompletedEventHandler getStallsCompleted;
        
        /// <remarks/>
        public event equipmentRegisterCompletedEventHandler equipmentRegisterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getFoodTypes", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getFoodTypes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FoodTypeRequest foodTypeRequest) {
            object[] results = this.Invoke("getFoodTypes", new object[] {
                        validateInfo,
                        foodTypeRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFoodTypesAsync(ValidateInfo validateInfo, FoodTypeRequest foodTypeRequest) {
            this.getFoodTypesAsync(validateInfo, foodTypeRequest, null);
        }
        
        /// <remarks/>
        public void getFoodTypesAsync(ValidateInfo validateInfo, FoodTypeRequest foodTypeRequest, object userState) {
            if ((this.getFoodTypesOperationCompleted == null)) {
                this.getFoodTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFoodTypesOperationCompleted);
            }
            this.InvokeAsync("getFoodTypes", new object[] {
                        validateInfo,
                        foodTypeRequest}, this.getFoodTypesOperationCompleted, userState);
        }
        
        private void OngetFoodTypesOperationCompleted(object arg) {
            if ((this.getFoodTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFoodTypesCompleted(this, new getFoodTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:uploadPlatformStallData", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string uploadPlatformStallData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateIpInfo validateIpInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OtherPlatformRequest stallDataRequest) {
            object[] results = this.Invoke("uploadPlatformStallData", new object[] {
                        validateIpInfo,
                        stallDataRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadPlatformStallDataAsync(ValidateIpInfo validateIpInfo, OtherPlatformRequest stallDataRequest) {
            this.uploadPlatformStallDataAsync(validateIpInfo, stallDataRequest, null);
        }
        
        /// <remarks/>
        public void uploadPlatformStallDataAsync(ValidateIpInfo validateIpInfo, OtherPlatformRequest stallDataRequest, object userState) {
            if ((this.uploadPlatformStallDataOperationCompleted == null)) {
                this.uploadPlatformStallDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadPlatformStallDataOperationCompleted);
            }
            this.InvokeAsync("uploadPlatformStallData", new object[] {
                        validateIpInfo,
                        stallDataRequest}, this.uploadPlatformStallDataOperationCompleted, userState);
        }
        
        private void OnuploadPlatformStallDataOperationCompleted(object arg) {
            if ((this.uploadPlatformStallDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadPlatformStallDataCompleted(this, new uploadPlatformStallDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:uploadPlatformDetectionData", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string uploadPlatformDetectionData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateIpInfo validateIpInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OtherPlatformRequest detectionDataRequest) {
            object[] results = this.Invoke("uploadPlatformDetectionData", new object[] {
                        validateIpInfo,
                        detectionDataRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadPlatformDetectionDataAsync(ValidateIpInfo validateIpInfo, OtherPlatformRequest detectionDataRequest) {
            this.uploadPlatformDetectionDataAsync(validateIpInfo, detectionDataRequest, null);
        }
        
        /// <remarks/>
        public void uploadPlatformDetectionDataAsync(ValidateIpInfo validateIpInfo, OtherPlatformRequest detectionDataRequest, object userState) {
            if ((this.uploadPlatformDetectionDataOperationCompleted == null)) {
                this.uploadPlatformDetectionDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadPlatformDetectionDataOperationCompleted);
            }
            this.InvokeAsync("uploadPlatformDetectionData", new object[] {
                        validateIpInfo,
                        detectionDataRequest}, this.uploadPlatformDetectionDataOperationCompleted, userState);
        }
        
        private void OnuploadPlatformDetectionDataOperationCompleted(object arg) {
            if ((this.uploadPlatformDetectionDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadPlatformDetectionDataCompleted(this, new uploadPlatformDetectionDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:uploadGps", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string uploadGps([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GPSRequest gpsRequest) {
            object[] results = this.Invoke("uploadGps", new object[] {
                        validateInfo,
                        gpsRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadGpsAsync(ValidateInfo validateInfo, GPSRequest gpsRequest) {
            this.uploadGpsAsync(validateInfo, gpsRequest, null);
        }
        
        /// <remarks/>
        public void uploadGpsAsync(ValidateInfo validateInfo, GPSRequest gpsRequest, object userState) {
            if ((this.uploadGpsOperationCompleted == null)) {
                this.uploadGpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadGpsOperationCompleted);
            }
            this.InvokeAsync("uploadGps", new object[] {
                        validateInfo,
                        gpsRequest}, this.uploadGpsOperationCompleted, userState);
        }
        
        private void OnuploadGpsOperationCompleted(object arg) {
            if ((this.uploadGpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadGpsCompleted(this, new uploadGpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:uploadPlatformEnterpriseData", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string uploadPlatformEnterpriseData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateIpInfo validateIpInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OtherPlatformRequest enterpriseDataRequest) {
            object[] results = this.Invoke("uploadPlatformEnterpriseData", new object[] {
                        validateIpInfo,
                        enterpriseDataRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadPlatformEnterpriseDataAsync(ValidateIpInfo validateIpInfo, OtherPlatformRequest enterpriseDataRequest) {
            this.uploadPlatformEnterpriseDataAsync(validateIpInfo, enterpriseDataRequest, null);
        }
        
        /// <remarks/>
        public void uploadPlatformEnterpriseDataAsync(ValidateIpInfo validateIpInfo, OtherPlatformRequest enterpriseDataRequest, object userState) {
            if ((this.uploadPlatformEnterpriseDataOperationCompleted == null)) {
                this.uploadPlatformEnterpriseDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadPlatformEnterpriseDataOperationCompleted);
            }
            this.InvokeAsync("uploadPlatformEnterpriseData", new object[] {
                        validateIpInfo,
                        enterpriseDataRequest}, this.uploadPlatformEnterpriseDataOperationCompleted, userState);
        }
        
        private void OnuploadPlatformEnterpriseDataOperationCompleted(object arg) {
            if ((this.uploadPlatformEnterpriseDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadPlatformEnterpriseDataCompleted(this, new uploadPlatformEnterpriseDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getTestItems", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getTestItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TestItemRequest testItemRequest) {
            object[] results = this.Invoke("getTestItems", new object[] {
                        validateInfo,
                        testItemRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTestItemsAsync(ValidateInfo validateInfo, TestItemRequest testItemRequest) {
            this.getTestItemsAsync(validateInfo, testItemRequest, null);
        }
        
        /// <remarks/>
        public void getTestItemsAsync(ValidateInfo validateInfo, TestItemRequest testItemRequest, object userState) {
            if ((this.getTestItemsOperationCompleted == null)) {
                this.getTestItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTestItemsOperationCompleted);
            }
            this.InvokeAsync("getTestItems", new object[] {
                        validateInfo,
                        testItemRequest}, this.getTestItemsOperationCompleted, userState);
        }
        
        private void OngetTestItemsOperationCompleted(object arg) {
            if ((this.getTestItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTestItemsCompleted(this, new getTestItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getEnterprises", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getEnterprises([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EnterpriseRequest enterpriseRequest) {
            object[] results = this.Invoke("getEnterprises", new object[] {
                        validateInfo,
                        enterpriseRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getEnterprisesAsync(ValidateInfo validateInfo, EnterpriseRequest enterpriseRequest) {
            this.getEnterprisesAsync(validateInfo, enterpriseRequest, null);
        }
        
        /// <remarks/>
        public void getEnterprisesAsync(ValidateInfo validateInfo, EnterpriseRequest enterpriseRequest, object userState) {
            if ((this.getEnterprisesOperationCompleted == null)) {
                this.getEnterprisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEnterprisesOperationCompleted);
            }
            this.InvokeAsync("getEnterprises", new object[] {
                        validateInfo,
                        enterpriseRequest}, this.getEnterprisesOperationCompleted, userState);
        }
        
        private void OngetEnterprisesOperationCompleted(object arg) {
            if ((this.getEnterprisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEnterprisesCompleted(this, new getEnterprisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:uploadDetectionData", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string uploadDetectionData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DetectionDataRequest detectionDataRequest) {
            object[] results = this.Invoke("uploadDetectionData", new object[] {
                        validateInfo,
                        detectionDataRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadDetectionDataAsync(ValidateInfo validateInfo, DetectionDataRequest detectionDataRequest) {
            this.uploadDetectionDataAsync(validateInfo, detectionDataRequest, null);
        }
        
        /// <remarks/>
        public void uploadDetectionDataAsync(ValidateInfo validateInfo, DetectionDataRequest detectionDataRequest, object userState) {
            if ((this.uploadDetectionDataOperationCompleted == null)) {
                this.uploadDetectionDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadDetectionDataOperationCompleted);
            }
            this.InvokeAsync("uploadDetectionData", new object[] {
                        validateInfo,
                        detectionDataRequest}, this.uploadDetectionDataOperationCompleted, userState);
        }
        
        private void OnuploadDetectionDataOperationCompleted(object arg) {
            if ((this.uploadDetectionDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadDetectionDataCompleted(this, new uploadDetectionDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getProducts", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getProducts([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProductRequest productRequest) {
            object[] results = this.Invoke("getProducts", new object[] {
                        validateInfo,
                        productRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getProductsAsync(ValidateInfo validateInfo, ProductRequest productRequest) {
            this.getProductsAsync(validateInfo, productRequest, null);
        }
        
        /// <remarks/>
        public void getProductsAsync(ValidateInfo validateInfo, ProductRequest productRequest, object userState) {
            if ((this.getProductsOperationCompleted == null)) {
                this.getProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProductsOperationCompleted);
            }
            this.InvokeAsync("getProducts", new object[] {
                        validateInfo,
                        productRequest}, this.getProductsOperationCompleted, userState);
        }
        
        private void OngetProductsOperationCompleted(object arg) {
            if ((this.getProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProductsCompleted(this, new getProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getStalls", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getStalls([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] StallRequest stallRequest) {
            object[] results = this.Invoke("getStalls", new object[] {
                        validateInfo,
                        stallRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStallsAsync(ValidateInfo validateInfo, StallRequest stallRequest) {
            this.getStallsAsync(validateInfo, stallRequest, null);
        }
        
        /// <remarks/>
        public void getStallsAsync(ValidateInfo validateInfo, StallRequest stallRequest, object userState) {
            if ((this.getStallsOperationCompleted == null)) {
                this.getStallsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStallsOperationCompleted);
            }
            this.InvokeAsync("getStalls", new object[] {
                        validateInfo,
                        stallRequest}, this.getStallsOperationCompleted, userState);
        }
        
        private void OngetStallsOperationCompleted(object arg) {
            if ((this.getStallsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStallsCompleted(this, new getStallsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:equipmentRegister", RequestNamespace="http://webservice.lhfs.com", ResponseNamespace="http://webservice.lhfs.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string equipmentRegister([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateInfo validateInfo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EquipmentRequest equipmentRequest) {
            object[] results = this.Invoke("equipmentRegister", new object[] {
                        validateInfo,
                        equipmentRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void equipmentRegisterAsync(ValidateInfo validateInfo, EquipmentRequest equipmentRequest) {
            this.equipmentRegisterAsync(validateInfo, equipmentRequest, null);
        }
        
        /// <remarks/>
        public void equipmentRegisterAsync(ValidateInfo validateInfo, EquipmentRequest equipmentRequest, object userState) {
            if ((this.equipmentRegisterOperationCompleted == null)) {
                this.equipmentRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnequipmentRegisterOperationCompleted);
            }
            this.InvokeAsync("equipmentRegister", new object[] {
                        validateInfo,
                        equipmentRequest}, this.equipmentRegisterOperationCompleted, userState);
        }
        
        private void OnequipmentRegisterOperationCompleted(object arg) {
            if ((this.equipmentRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.equipmentRegisterCompleted(this, new equipmentRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class ValidateInfo {
        
        private string keyField;
        
        private string userNameField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class EquipmentRequest {
        
        private string eqManufacturerField;
        
        private string eqModelField;
        
        private string eqNameField;
        
        private string eqNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqManufacturer {
            get {
                return this.eqManufacturerField;
            }
            set {
                this.eqManufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqModel {
            get {
                return this.eqModelField;
            }
            set {
                this.eqModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqName {
            get {
                return this.eqNameField;
            }
            set {
                this.eqNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqNum {
            get {
                return this.eqNumField;
            }
            set {
                this.eqNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class StallRequest {
        
        private System.Nullable<int> curPageField;
        
        private bool curPageFieldSpecified;
        
        private string enterpriseIdField;
        
        private string ifOrderField;
        
        private string isDescField;
        
        private string stallNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> curPage {
            get {
                return this.curPageField;
            }
            set {
                this.curPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool curPageSpecified {
            get {
                return this.curPageFieldSpecified;
            }
            set {
                this.curPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string enterpriseId {
            get {
                return this.enterpriseIdField;
            }
            set {
                this.enterpriseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ifOrder {
            get {
                return this.ifOrderField;
            }
            set {
                this.ifOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string stallNumber {
            get {
                return this.stallNumberField;
            }
            set {
                this.stallNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class ProductRequest {
        
        private System.Nullable<int> curPageField;
        
        private bool curPageFieldSpecified;
        
        private string endTimeField;
        
        private string enterpriseIdField;
        
        private string ifOrderField;
        
        private string isDescField;
        
        private string sampleNumField;
        
        private string stallNumberField;
        
        private string startTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> curPage {
            get {
                return this.curPageField;
            }
            set {
                this.curPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool curPageSpecified {
            get {
                return this.curPageFieldSpecified;
            }
            set {
                this.curPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string enterpriseId {
            get {
                return this.enterpriseIdField;
            }
            set {
                this.enterpriseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ifOrder {
            get {
                return this.ifOrderField;
            }
            set {
                this.ifOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sampleNum {
            get {
                return this.sampleNumField;
            }
            set {
                this.sampleNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string stallNumber {
            get {
                return this.stallNumberField;
            }
            set {
                this.stallNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class DetectionDataRequest {
        
        private string createDateField;
        
        private string enterpriseIdField;
        
        private string eqModelField;
        
        private string eqNumField;
        
        private string foodTypeIdField;
        
        private string resultField;
        
        private string sampleNameField;
        
        private string sampleNumField;
        
        private string stallNumField;
        
        private string standardField;
        
        private string standardDataField;
        
        private string testDataField;
        
        private string testItemIdField;
        
        private string testUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string enterpriseId {
            get {
                return this.enterpriseIdField;
            }
            set {
                this.enterpriseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqModel {
            get {
                return this.eqModelField;
            }
            set {
                this.eqModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqNum {
            get {
                return this.eqNumField;
            }
            set {
                this.eqNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string foodTypeId {
            get {
                return this.foodTypeIdField;
            }
            set {
                this.foodTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sampleName {
            get {
                return this.sampleNameField;
            }
            set {
                this.sampleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sampleNum {
            get {
                return this.sampleNumField;
            }
            set {
                this.sampleNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string stallNum {
            get {
                return this.stallNumField;
            }
            set {
                this.stallNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string standardData {
            get {
                return this.standardDataField;
            }
            set {
                this.standardDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testData {
            get {
                return this.testDataField;
            }
            set {
                this.testDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testItemId {
            get {
                return this.testItemIdField;
            }
            set {
                this.testItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testUnit {
            get {
                return this.testUnitField;
            }
            set {
                this.testUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class EnterpriseRequest {
        
        private System.Nullable<int> curPageField;
        
        private bool curPageFieldSpecified;
        
        private string enterpriseNameField;
        
        private string ifOrderField;
        
        private string isDescField;
        
        private string typesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> curPage {
            get {
                return this.curPageField;
            }
            set {
                this.curPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool curPageSpecified {
            get {
                return this.curPageFieldSpecified;
            }
            set {
                this.curPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string enterpriseName {
            get {
                return this.enterpriseNameField;
            }
            set {
                this.enterpriseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ifOrder {
            get {
                return this.ifOrderField;
            }
            set {
                this.ifOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class TestItemRequest {
        
        private System.Nullable<int> curPageField;
        
        private bool curPageFieldSpecified;
        
        private string ifOrderField;
        
        private string isAllField;
        
        private string isDescField;
        
        private string testItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> curPage {
            get {
                return this.curPageField;
            }
            set {
                this.curPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool curPageSpecified {
            get {
                return this.curPageFieldSpecified;
            }
            set {
                this.curPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ifOrder {
            get {
                return this.ifOrderField;
            }
            set {
                this.ifOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isAll {
            get {
                return this.isAllField;
            }
            set {
                this.isAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testItem {
            get {
                return this.testItemField;
            }
            set {
                this.testItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class GPSRequest {
        
        private string dateField;
        
        private string eqModelField;
        
        private string eqNumField;
        
        private string latField;
        
        private string lngField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqModel {
            get {
                return this.eqModelField;
            }
            set {
                this.eqModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eqNum {
            get {
                return this.eqNumField;
            }
            set {
                this.eqNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class OtherPlatformRequest {
        
        private string jsonDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string jsonData {
            get {
                return this.jsonDataField;
            }
            set {
                this.jsonDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class ValidateIpInfo {
        
        private string ipField;
        
        private string keyField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.webservice.lhfs.com/xsd")]
    public partial class FoodTypeRequest {
        
        private System.Nullable<int> curPageField;
        
        private bool curPageFieldSpecified;
        
        private string foodTypeField;
        
        private string ifOrderField;
        
        private string isAllField;
        
        private string isDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> curPage {
            get {
                return this.curPageField;
            }
            set {
                this.curPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool curPageSpecified {
            get {
                return this.curPageFieldSpecified;
            }
            set {
                this.curPageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string foodType {
            get {
                return this.foodTypeField;
            }
            set {
                this.foodTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ifOrder {
            get {
                return this.ifOrderField;
            }
            set {
                this.ifOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isAll {
            get {
                return this.isAllField;
            }
            set {
                this.isAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getFoodTypesCompletedEventHandler(object sender, getFoodTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFoodTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFoodTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void uploadPlatformStallDataCompletedEventHandler(object sender, uploadPlatformStallDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadPlatformStallDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadPlatformStallDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void uploadPlatformDetectionDataCompletedEventHandler(object sender, uploadPlatformDetectionDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadPlatformDetectionDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadPlatformDetectionDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void uploadGpsCompletedEventHandler(object sender, uploadGpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadGpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadGpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void uploadPlatformEnterpriseDataCompletedEventHandler(object sender, uploadPlatformEnterpriseDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadPlatformEnterpriseDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadPlatformEnterpriseDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getTestItemsCompletedEventHandler(object sender, getTestItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTestItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTestItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getEnterprisesCompletedEventHandler(object sender, getEnterprisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEnterprisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEnterprisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void uploadDetectionDataCompletedEventHandler(object sender, uploadDetectionDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadDetectionDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadDetectionDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getProductsCompletedEventHandler(object sender, getProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getStallsCompletedEventHandler(object sender, getStallsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void equipmentRegisterCompletedEventHandler(object sender, equipmentRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class equipmentRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal equipmentRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591