//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationModel.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://111.1.62.181/Put.jws", ConfigurationName="ServiceReference1.Put")]
    public interface Put {
        
        // CODEGEN: 消息 saveRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://111.1.62.181/Put.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WorkstationModel.ServiceReference1.saveResponse save(WorkstationModel.ServiceReference1.saveRequest request);
        
        // CODEGEN: 消息 saveExRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://111.1.62.181/Put.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WorkstationModel.ServiceReference1.saveExResponse saveEx(WorkstationModel.ServiceReference1.saveExRequest request);
        
        // CODEGEN: 消息 saveExScRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://111.1.62.181/Put.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WorkstationModel.ServiceReference1.saveExScResponse saveExSc(WorkstationModel.ServiceReference1.saveExScRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class saveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string checkPrj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string clazz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string mode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string dept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string checker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string demoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string pdtSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string cksAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string formats;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public object valueFmt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public object valueTru;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string oneResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public System.DateTime checkDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public System.DateTime uploadDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string factorys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public System.DateTime factoryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string comp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string compType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string macComp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public System.DateTime cksGetDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string results;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string id;
        
        public saveRequest() {
        }
        
        public saveRequest(
                    string name, 
                    string checkPrj, 
                    string clazz, 
                    string mode, 
                    string dept, 
                    string checker, 
                    string demoId, 
                    string pdtSource, 
                    string cksAddr, 
                    string formats, 
                    object valueFmt, 
                    object valueTru, 
                    string oneResults, 
                    System.DateTime checkDate, 
                    System.DateTime uploadDate, 
                    string factorys, 
                    System.DateTime factoryDate, 
                    string comp, 
                    string compType, 
                    string macComp, 
                    System.DateTime cksGetDate, 
                    string results, 
                    string id) {
            this.name = name;
            this.checkPrj = checkPrj;
            this.clazz = clazz;
            this.mode = mode;
            this.dept = dept;
            this.checker = checker;
            this.demoId = demoId;
            this.pdtSource = pdtSource;
            this.cksAddr = cksAddr;
            this.formats = formats;
            this.valueFmt = valueFmt;
            this.valueTru = valueTru;
            this.oneResults = oneResults;
            this.checkDate = checkDate;
            this.uploadDate = uploadDate;
            this.factorys = factorys;
            this.factoryDate = factoryDate;
            this.comp = comp;
            this.compType = compType;
            this.macComp = macComp;
            this.cksGetDate = cksGetDate;
            this.results = results;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://111.1.62.181/Put.jws", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saveReturn;
        
        public saveResponse() {
        }
        
        public saveResponse(string saveReturn) {
            this.saveReturn = saveReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveEx", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class saveExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string checkPrj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string clazz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string mode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string dept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string checker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string demoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string pdtSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string cksAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string formats;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string valueFmt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string valueTru;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string oneResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public System.DateTime checkDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public System.DateTime uploadDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string factorys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public System.DateTime factoryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string comp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string compType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string macComp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public System.DateTime cksGetDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string results;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string id;
        
        public saveExRequest() {
        }
        
        public saveExRequest(
                    string name, 
                    string checkPrj, 
                    string clazz, 
                    string mode, 
                    string dept, 
                    string checker, 
                    string demoId, 
                    string pdtSource, 
                    string cksAddr, 
                    string formats, 
                    string valueFmt, 
                    string valueTru, 
                    string oneResults, 
                    System.DateTime checkDate, 
                    System.DateTime uploadDate, 
                    string factorys, 
                    System.DateTime factoryDate, 
                    string comp, 
                    string compType, 
                    string macComp, 
                    System.DateTime cksGetDate, 
                    string results, 
                    string id) {
            this.name = name;
            this.checkPrj = checkPrj;
            this.clazz = clazz;
            this.mode = mode;
            this.dept = dept;
            this.checker = checker;
            this.demoId = demoId;
            this.pdtSource = pdtSource;
            this.cksAddr = cksAddr;
            this.formats = formats;
            this.valueFmt = valueFmt;
            this.valueTru = valueTru;
            this.oneResults = oneResults;
            this.checkDate = checkDate;
            this.uploadDate = uploadDate;
            this.factorys = factorys;
            this.factoryDate = factoryDate;
            this.comp = comp;
            this.compType = compType;
            this.macComp = macComp;
            this.cksGetDate = cksGetDate;
            this.results = results;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveExResponse", WrapperNamespace="http://111.1.62.181/Put.jws", IsWrapped=true)]
    public partial class saveExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saveExReturn;
        
        public saveExResponse() {
        }
        
        public saveExResponse(string saveExReturn) {
            this.saveExReturn = saveExReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveExSc", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class saveExScRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string checkPrj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string clazz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string mode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string dept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string checker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string demoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string pdtSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string cksAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string formats;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string valueFmt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string valueTru;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string oneResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public System.DateTime checkDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public System.DateTime uploadDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string factorys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public System.DateTime factoryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string comp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string compType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string macComp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public System.DateTime cksGetDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string results;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string id;
        
        public saveExScRequest() {
        }
        
        public saveExScRequest(
                    string name, 
                    string checkPrj, 
                    string clazz, 
                    string mode, 
                    string dept, 
                    string checker, 
                    string demoId, 
                    string pdtSource, 
                    string cksAddr, 
                    string formats, 
                    string valueFmt, 
                    string valueTru, 
                    string oneResults, 
                    System.DateTime checkDate, 
                    System.DateTime uploadDate, 
                    string factorys, 
                    System.DateTime factoryDate, 
                    string comp, 
                    string compType, 
                    string macComp, 
                    System.DateTime cksGetDate, 
                    string results, 
                    string id) {
            this.name = name;
            this.checkPrj = checkPrj;
            this.clazz = clazz;
            this.mode = mode;
            this.dept = dept;
            this.checker = checker;
            this.demoId = demoId;
            this.pdtSource = pdtSource;
            this.cksAddr = cksAddr;
            this.formats = formats;
            this.valueFmt = valueFmt;
            this.valueTru = valueTru;
            this.oneResults = oneResults;
            this.checkDate = checkDate;
            this.uploadDate = uploadDate;
            this.factorys = factorys;
            this.factoryDate = factoryDate;
            this.comp = comp;
            this.compType = compType;
            this.macComp = macComp;
            this.cksGetDate = cksGetDate;
            this.results = results;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveExScResponse", WrapperNamespace="http://111.1.62.181/Put.jws", IsWrapped=true)]
    public partial class saveExScResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saveExScReturn;
        
        public saveExScResponse() {
        }
        
        public saveExScResponse(string saveExScReturn) {
            this.saveExScReturn = saveExScReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PutChannel : WorkstationModel.ServiceReference1.Put, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutClient : System.ServiceModel.ClientBase<WorkstationModel.ServiceReference1.Put>, WorkstationModel.ServiceReference1.Put {
        
        public PutClient() {
        }
        
        public PutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorkstationModel.ServiceReference1.saveResponse WorkstationModel.ServiceReference1.Put.save(WorkstationModel.ServiceReference1.saveRequest request) {
            return base.Channel.save(request);
        }
        
        public string save(
                    string name, 
                    string checkPrj, 
                    string clazz, 
                    string mode, 
                    string dept, 
                    string checker, 
                    string demoId, 
                    string pdtSource, 
                    string cksAddr, 
                    string formats, 
                    object valueFmt, 
                    object valueTru, 
                    string oneResults, 
                    System.DateTime checkDate, 
                    System.DateTime uploadDate, 
                    string factorys, 
                    System.DateTime factoryDate, 
                    string comp, 
                    string compType, 
                    string macComp, 
                    System.DateTime cksGetDate, 
                    string results, 
                    string id) {
            WorkstationModel.ServiceReference1.saveRequest inValue = new WorkstationModel.ServiceReference1.saveRequest();
            inValue.name = name;
            inValue.checkPrj = checkPrj;
            inValue.clazz = clazz;
            inValue.mode = mode;
            inValue.dept = dept;
            inValue.checker = checker;
            inValue.demoId = demoId;
            inValue.pdtSource = pdtSource;
            inValue.cksAddr = cksAddr;
            inValue.formats = formats;
            inValue.valueFmt = valueFmt;
            inValue.valueTru = valueTru;
            inValue.oneResults = oneResults;
            inValue.checkDate = checkDate;
            inValue.uploadDate = uploadDate;
            inValue.factorys = factorys;
            inValue.factoryDate = factoryDate;
            inValue.comp = comp;
            inValue.compType = compType;
            inValue.macComp = macComp;
            inValue.cksGetDate = cksGetDate;
            inValue.results = results;
            inValue.id = id;
            WorkstationModel.ServiceReference1.saveResponse retVal = ((WorkstationModel.ServiceReference1.Put)(this)).save(inValue);
            return retVal.saveReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorkstationModel.ServiceReference1.saveExResponse WorkstationModel.ServiceReference1.Put.saveEx(WorkstationModel.ServiceReference1.saveExRequest request) {
            return base.Channel.saveEx(request);
        }
        
        public string saveEx(
                    string name, 
                    string checkPrj, 
                    string clazz, 
                    string mode, 
                    string dept, 
                    string checker, 
                    string demoId, 
                    string pdtSource, 
                    string cksAddr, 
                    string formats, 
                    string valueFmt, 
                    string valueTru, 
                    string oneResults, 
                    System.DateTime checkDate, 
                    System.DateTime uploadDate, 
                    string factorys, 
                    System.DateTime factoryDate, 
                    string comp, 
                    string compType, 
                    string macComp, 
                    System.DateTime cksGetDate, 
                    string results, 
                    string id) {
            WorkstationModel.ServiceReference1.saveExRequest inValue = new WorkstationModel.ServiceReference1.saveExRequest();
            inValue.name = name;
            inValue.checkPrj = checkPrj;
            inValue.clazz = clazz;
            inValue.mode = mode;
            inValue.dept = dept;
            inValue.checker = checker;
            inValue.demoId = demoId;
            inValue.pdtSource = pdtSource;
            inValue.cksAddr = cksAddr;
            inValue.formats = formats;
            inValue.valueFmt = valueFmt;
            inValue.valueTru = valueTru;
            inValue.oneResults = oneResults;
            inValue.checkDate = checkDate;
            inValue.uploadDate = uploadDate;
            inValue.factorys = factorys;
            inValue.factoryDate = factoryDate;
            inValue.comp = comp;
            inValue.compType = compType;
            inValue.macComp = macComp;
            inValue.cksGetDate = cksGetDate;
            inValue.results = results;
            inValue.id = id;
            WorkstationModel.ServiceReference1.saveExResponse retVal = ((WorkstationModel.ServiceReference1.Put)(this)).saveEx(inValue);
            return retVal.saveExReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorkstationModel.ServiceReference1.saveExScResponse WorkstationModel.ServiceReference1.Put.saveExSc(WorkstationModel.ServiceReference1.saveExScRequest request) {
            return base.Channel.saveExSc(request);
        }
        
        public string saveExSc(
                    string name, 
                    string checkPrj, 
                    string clazz, 
                    string mode, 
                    string dept, 
                    string checker, 
                    string demoId, 
                    string pdtSource, 
                    string cksAddr, 
                    string formats, 
                    string valueFmt, 
                    string valueTru, 
                    string oneResults, 
                    System.DateTime checkDate, 
                    System.DateTime uploadDate, 
                    string factorys, 
                    System.DateTime factoryDate, 
                    string comp, 
                    string compType, 
                    string macComp, 
                    System.DateTime cksGetDate, 
                    string results, 
                    string id) {
            WorkstationModel.ServiceReference1.saveExScRequest inValue = new WorkstationModel.ServiceReference1.saveExScRequest();
            inValue.name = name;
            inValue.checkPrj = checkPrj;
            inValue.clazz = clazz;
            inValue.mode = mode;
            inValue.dept = dept;
            inValue.checker = checker;
            inValue.demoId = demoId;
            inValue.pdtSource = pdtSource;
            inValue.cksAddr = cksAddr;
            inValue.formats = formats;
            inValue.valueFmt = valueFmt;
            inValue.valueTru = valueTru;
            inValue.oneResults = oneResults;
            inValue.checkDate = checkDate;
            inValue.uploadDate = uploadDate;
            inValue.factorys = factorys;
            inValue.factoryDate = factoryDate;
            inValue.comp = comp;
            inValue.compType = compType;
            inValue.macComp = macComp;
            inValue.cksGetDate = cksGetDate;
            inValue.results = results;
            inValue.id = id;
            WorkstationModel.ServiceReference1.saveExScResponse retVal = ((WorkstationModel.ServiceReference1.Put)(this)).saveExSc(inValue);
            return retVal.saveExScReturn;
        }
    }
}
