#pragma checksum "..\..\..\..\xaml\Main\DataManagementWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "2FCA1D96D3466C4D9D753B728E68A2A2"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO.xaml.Main {
    
    
    /// <summary>
    /// DataManagementWindow
    /// </summary>
    public partial class DataManagementWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel WraPanel;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label fgdLabel1;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Fgd;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonManagementSample;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label fgdLabel2;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label jtjLabel1;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Jtj;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonManagementCompany;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label jtjLabel2;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label ghxLabel1;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Ghx;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonRecord;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label ghxLabel2;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label1;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border border1;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnReportSearch;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label2;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label zjsLabel1;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Zjs;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonTask;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label zjsLabel2;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/main/datamanagementwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 19 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.WraPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 3:
            this.fgdLabel1 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.Fgd = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.ButtonManagementSample = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            this.ButtonManagementSample.Click += new System.Windows.RoutedEventHandler(this.ButtonManagementSample_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.fgdLabel2 = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.jtjLabel1 = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.Jtj = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.ButtonManagementCompany = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            this.ButtonManagementCompany.Click += new System.Windows.RoutedEventHandler(this.ButtonManagementCompany_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.jtjLabel2 = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.ghxLabel1 = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.Ghx = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.ButtonRecord = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            this.ButtonRecord.Click += new System.Windows.RoutedEventHandler(this.ButtonRecord_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.ghxLabel2 = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.border1 = ((System.Windows.Controls.Border)(target));
            return;
            case 17:
            this.btnReportSearch = ((System.Windows.Controls.Button)(target));
            
            #line 58 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            this.btnReportSearch.Click += new System.Windows.RoutedEventHandler(this.btnReportSearch_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.label2 = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.zjsLabel1 = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.Zjs = ((System.Windows.Controls.Border)(target));
            return;
            case 21:
            this.ButtonTask = ((System.Windows.Controls.Button)(target));
            
            #line 68 "..\..\..\..\xaml\Main\DataManagementWindow.xaml"
            this.ButtonTask.Click += new System.Windows.RoutedEventHandler(this.ButtonTask_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.zjsLabel2 = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

