#pragma checksum "..\..\..\..\xaml\Dialog\SearchItem.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D6CA6B835BDD2E42E038BF2FDBFAE31ED388103C"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO.xaml.Dialog {
    
    
    /// <summary>
    /// SearchItem
    /// </summary>
    public partial class SearchItem : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label labelclose;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label1;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button InputItem;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Search;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DataGridRecord;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/dialog/searchitem.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 5 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            ((AIO.xaml.Dialog.SearchItem)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.labelclose = ((System.Windows.Controls.Label)(target));
            
            #line 12 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            this.labelclose.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.labelclose_MouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 12 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            this.labelclose.MouseEnter += new System.Windows.Input.MouseEventHandler(this.labelclose_MouseEnter);
            
            #line default
            #line hidden
            
            #line 12 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            this.labelclose.MouseLeave += new System.Windows.Input.MouseEventHandler(this.labelclose_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 3:
            this.label1 = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.txt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.InputItem = ((System.Windows.Controls.Button)(target));
            
            #line 17 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            this.InputItem.Click += new System.Windows.RoutedEventHandler(this.InputItem_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Search = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            this.Search.Click += new System.Windows.RoutedEventHandler(this.Search_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.DataGridRecord = ((System.Windows.Controls.DataGrid)(target));
            
            #line 19 "..\..\..\..\xaml\Dialog\SearchItem.xaml"
            this.DataGridRecord.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.DataGridRecord_LoadingRow);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

