#pragma checksum "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C53482CBEE9FC8FB394A3A47CF655F7CE0D34397"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO {
    
    
    /// <summary>
    /// JtjReportWindow
    /// </summary>
    public partial class JtjReportWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LabelInfo;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrint;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnToDetect;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button button1;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonUpdate;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Btn_ShowDatas;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtC;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox txtCalcCT;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCZ;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel WrapPanelChannel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/jiaotijin/jtjreportwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            ((AIO.JtjReportWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            
            #line 10 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            ((AIO.JtjReportWindow)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.Window_Closing);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 15 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            ((System.Windows.Controls.Label)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Label_MouseDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.LabelInfo = ((System.Windows.Controls.Label)(target));
            
            #line 16 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.LabelInfo.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.LabelInfo_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ButtonPrint = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.ButtonPrint.Click += new System.Windows.RoutedEventHandler(this.ButtonPrint_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BtnToDetect = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.BtnToDetect.Click += new System.Windows.RoutedEventHandler(this.BtnToDetect_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.button1 = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.button1.Click += new System.Windows.RoutedEventHandler(this.ButtonSave_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ButtonUpdate = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.ButtonUpdate.Click += new System.Windows.RoutedEventHandler(this.ButtonUpdate_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Btn_ShowDatas = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\xaml\Jiaotijin\JtjReportWindow.xaml"
            this.Btn_ShowDatas.Click += new System.Windows.RoutedEventHandler(this.Btn_ShowDatas_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.txtC = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.txtCalcCT = ((System.Windows.Controls.RichTextBox)(target));
            return;
            case 12:
            this.txtCZ = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.WrapPanelChannel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

