#pragma checksum "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "426C0875C5D19317371E7D92C9D5961E"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DYitj {
    
    
    /// <summary>
    /// JtjMeasureWindow
    /// </summary>
    public partial class JtjMeasureWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSampleTest;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel WrapPanelChannel;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas rootCanvasCh1;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line lineTCh1;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line lineCCh1;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle rectCh1;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DYitj;component/xaml/ganhuaxue/jtjmeasurewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
            ((DYitj.JtjMeasureWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            
            #line 9 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
            ((DYitj.JtjMeasureWindow)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.Window_Closing);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ButtonSampleTest = ((System.Windows.Controls.Button)(target));
            
            #line 20 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
            this.ButtonSampleTest.Click += new System.Windows.RoutedEventHandler(this.ButtonSampleTest_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\xaml\Ganhuaxue\JtjMeasureWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.WrapPanelChannel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 5:
            this.rootCanvasCh1 = ((System.Windows.Controls.Canvas)(target));
            return;
            case 6:
            this.lineTCh1 = ((System.Windows.Shapes.Line)(target));
            return;
            case 7:
            this.lineCCh1 = ((System.Windows.Shapes.Line)(target));
            return;
            case 8:
            this.rectCh1 = ((System.Windows.Shapes.Rectangle)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

