#pragma checksum "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D2958887E96DF11052FC33CE16E5FDF1CCFBB94D"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO {
    
    
    /// <summary>
    /// HmEditItemWindow
    /// </summary>
    public partial class HmEditItemWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonNext;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid gridMeausre;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxItemName;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxPassword;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxItemID;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxUnit;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxSampleNum;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel StackPanelHole;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridHole;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxConcentration;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxLiquidVolume;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxDilutionRatio;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxRequirements;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxA0;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxA1;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxA2;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TextBoxHintStr;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/heavymetal/hmedititemwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            ((AIO.HmEditItemWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            
            #line 10 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            ((AIO.HmEditItemWindow)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.Window_Closing);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 20 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ButtonNext = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.ButtonNext.Click += new System.Windows.RoutedEventHandler(this.ButtonNext_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.gridMeausre = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this.ComboBoxItemName = ((System.Windows.Controls.ComboBox)(target));
            
            #line 36 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.ComboBoxItemName.DropDownClosed += new System.EventHandler(this.ComboBoxItemName_DropDownClosed);
            
            #line default
            #line hidden
            
            #line 36 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.ComboBoxItemName.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ComboBoxItemName_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TextBoxPassword = ((System.Windows.Controls.TextBox)(target));
            
            #line 47 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxPassword.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxPassword_TextChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TextBoxItemID = ((System.Windows.Controls.TextBox)(target));
            
            #line 51 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxItemID.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxItemID_TextChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.TextBoxUnit = ((System.Windows.Controls.TextBox)(target));
            
            #line 53 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxUnit.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxUnit_TextChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.TextBoxSampleNum = ((System.Windows.Controls.TextBox)(target));
            
            #line 57 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxSampleNum.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxSampleNum_TextChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.StackPanelHole = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 11:
            this.GridHole = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.TextBoxConcentration = ((System.Windows.Controls.TextBox)(target));
            
            #line 69 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxConcentration.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxConcentration_TextChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.TextBoxLiquidVolume = ((System.Windows.Controls.TextBox)(target));
            
            #line 71 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxLiquidVolume.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxLiquidVolume_TextChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.TextBoxDilutionRatio = ((System.Windows.Controls.TextBox)(target));
            
            #line 75 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxDilutionRatio.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxDilutionRatio_TextChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.TextBoxRequirements = ((System.Windows.Controls.TextBox)(target));
            
            #line 77 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxRequirements.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxRequirements_TextChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.TextBoxA0 = ((System.Windows.Controls.TextBox)(target));
            
            #line 84 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxA0.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxA0_TextChanged);
            
            #line default
            #line hidden
            return;
            case 17:
            this.TextBoxA1 = ((System.Windows.Controls.TextBox)(target));
            
            #line 86 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxA1.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxA1_TextChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.TextBoxA2 = ((System.Windows.Controls.TextBox)(target));
            
            #line 88 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxA2.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxA2_TextChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.TextBoxHintStr = ((System.Windows.Controls.TextBox)(target));
            
            #line 93 "..\..\..\..\xaml\HeavyMetal\HmEditItemWindow.xaml"
            this.TextBoxHintStr.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TextBoxHintStr_TextChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

