#pragma checksum "..\..\..\..\xaml\Main\SettingsWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "2C5EC7EED51D759D2D4B5828E652D6C4"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AIO {
    
    
    /// <summary>
    /// SettingsWindow
    /// </summary>
    public partial class SettingsWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 25 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPrev;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Update;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel skpFgdTop;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxADPort;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonADPortTest;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonShowAD;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCheckError;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel skpSxtLine1;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSXT1Port;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSXT1PortTest;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSXT2Port;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSXT2PorTest;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel skpSxtLine2;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSXT3Port;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSXT3PortTest;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxSXT4Port;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonSXT4PorTest;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxPRINTPort;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonPRINTPortTest;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel skpZjs;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ComboBoxHMPort;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonHMPortTest;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel sp_ZH;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_DeviceId;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_SaveDeviceId;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_settingZH;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel skpFgdC;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel StackPanelLEDSettings;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBoxServerAddr;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button buttonServerTest;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBoxRegisterID;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox textBoxRegisterPassword;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textCheckPlaceCode;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBoxCheckNumber;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBoxCheckName;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBoxCheckType;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBoxCheckOrg;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCompany;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCheckItems;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button buttonCehckSync;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DY-Detector;component/xaml/main/settingswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 11 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            ((AIO.SettingsWindow)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.Window_Closing);
            
            #line default
            #line hidden
            
            #line 11 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            ((AIO.SettingsWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ButtonPrev = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonPrev.Click += new System.Windows.RoutedEventHandler(this.ButtonPrev_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btn_Update = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.btn_Update.Click += new System.Windows.RoutedEventHandler(this.btn_Update_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.skpFgdTop = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 5:
            this.ComboBoxADPort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 44 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxADPort.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            
            #line 44 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxADPort.DropDownClosed += new System.EventHandler(this.ComboBoxADPort_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ButtonADPortTest = ((System.Windows.Controls.Button)(target));
            
            #line 45 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonADPortTest.Click += new System.Windows.RoutedEventHandler(this.ButtonADPortTest_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ButtonShowAD = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonShowAD.Click += new System.Windows.RoutedEventHandler(this.ButtonShowAD_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BtnCheckError = ((System.Windows.Controls.Button)(target));
            
            #line 51 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.BtnCheckError.Click += new System.Windows.RoutedEventHandler(this.BtnCheckError_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.skpSxtLine1 = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 10:
            this.ComboBoxSXT1Port = ((System.Windows.Controls.ComboBox)(target));
            
            #line 58 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT1Port.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            
            #line 58 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT1Port.DropDownClosed += new System.EventHandler(this.ComboBoxSXT1Port_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 11:
            this.ButtonSXT1PortTest = ((System.Windows.Controls.Button)(target));
            
            #line 59 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonSXT1PortTest.Click += new System.Windows.RoutedEventHandler(this.ButtonSXT1PortTest_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ComboBoxSXT2Port = ((System.Windows.Controls.ComboBox)(target));
            
            #line 63 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT2Port.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            
            #line 63 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT2Port.DropDownClosed += new System.EventHandler(this.ComboBoxSXT2Port_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ButtonSXT2PorTest = ((System.Windows.Controls.Button)(target));
            
            #line 64 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonSXT2PorTest.Click += new System.Windows.RoutedEventHandler(this.ButtonSXT2PorTest_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.skpSxtLine2 = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 15:
            this.ComboBoxSXT3Port = ((System.Windows.Controls.ComboBox)(target));
            
            #line 71 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT3Port.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            
            #line 71 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT3Port.DropDownClosed += new System.EventHandler(this.ComboBoxSXT3Port_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 16:
            this.ButtonSXT3PortTest = ((System.Windows.Controls.Button)(target));
            
            #line 72 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonSXT3PortTest.Click += new System.Windows.RoutedEventHandler(this.ButtonSXT3PortTest_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.ComboBoxSXT4Port = ((System.Windows.Controls.ComboBox)(target));
            
            #line 76 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT4Port.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            
            #line 76 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxSXT4Port.DropDownClosed += new System.EventHandler(this.ComboBoxSXT4Port_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 18:
            this.ButtonSXT4PorTest = ((System.Windows.Controls.Button)(target));
            
            #line 77 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonSXT4PorTest.Click += new System.Windows.RoutedEventHandler(this.ButtonSXT4PorTest_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.ComboBoxPRINTPort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 83 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxPRINTPort.DropDownClosed += new System.EventHandler(this.ComboBoxPRINTPort_DropDownClosed);
            
            #line default
            #line hidden
            
            #line 83 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxPRINTPort.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            return;
            case 20:
            this.ButtonPRINTPortTest = ((System.Windows.Controls.Button)(target));
            
            #line 84 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonPRINTPortTest.Click += new System.Windows.RoutedEventHandler(this.ButtonPRINTPortTest_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.skpZjs = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 22:
            this.ComboBoxHMPort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 88 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxHMPort.DropDownClosed += new System.EventHandler(this.ComboBoxHMPort_DropDownClosed);
            
            #line default
            #line hidden
            
            #line 88 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ComboBoxHMPort.DropDownOpened += new System.EventHandler(this.ComboBoxPort_DropDownOpened);
            
            #line default
            #line hidden
            return;
            case 23:
            this.ButtonHMPortTest = ((System.Windows.Controls.Button)(target));
            
            #line 89 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.ButtonHMPortTest.Click += new System.Windows.RoutedEventHandler(this.ButtonHMPortTest_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.sp_ZH = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 25:
            this.tb_DeviceId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 26:
            this.btn_SaveDeviceId = ((System.Windows.Controls.Button)(target));
            
            #line 96 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.btn_SaveDeviceId.Click += new System.Windows.RoutedEventHandler(this.btn_SaveDeviceId_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.btn_settingZH = ((System.Windows.Controls.Button)(target));
            
            #line 99 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.btn_settingZH.Click += new System.Windows.RoutedEventHandler(this.btn_settingZH_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.skpFgdC = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 29:
            this.StackPanelLEDSettings = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 30:
            this.textBoxServerAddr = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.buttonServerTest = ((System.Windows.Controls.Button)(target));
            
            #line 116 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.buttonServerTest.Click += new System.Windows.RoutedEventHandler(this.buttonServerTest_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.textBoxRegisterID = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.textBoxRegisterPassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 34:
            this.textCheckPlaceCode = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.textBoxCheckNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 36:
            this.textBoxCheckName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 37:
            this.textBoxCheckType = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.textBoxCheckOrg = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.btnCompany = ((System.Windows.Controls.Button)(target));
            
            #line 150 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.btnCompany.Click += new System.Windows.RoutedEventHandler(this.BtnCompany_Click);
            
            #line default
            #line hidden
            return;
            case 40:
            this.btnCheckItems = ((System.Windows.Controls.Button)(target));
            
            #line 151 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.btnCheckItems.Click += new System.Windows.RoutedEventHandler(this.btnCheckItems_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            this.buttonCehckSync = ((System.Windows.Controls.Button)(target));
            
            #line 152 "..\..\..\..\xaml\Main\SettingsWindow.xaml"
            this.buttonCehckSync.Click += new System.Windows.RoutedEventHandler(this.buttonCehckSync_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

